### ISSUE TITLE
No such file or directory: '/tmp/tmpl9n2hsu3/data.mat'

### ISSUE THREAD

**Issue by Biswajitks1** [daniellerch/aletheia#40]
I have installed every requirement but still getting the following error:-

2025-05-12 19:35:38.812191: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-05-12 19:35:38.812234: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-05-12 19:35:38.813552: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-05-12 19:35:38.820383: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-05-12 19:35:40.525294: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
'dev' not provided, using: CPU
Running with CPU. It could be very slow!
2025-05-12 19:35:42.517676: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2025-05-12 19:35:42.517719: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:129] retrieving CUDA diagnostic information for host: pop-os
2025-05-12 19:35:42.517726: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:136] hostname: pop-os
2025-05-12 19:35:42.517847: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:159] libcuda reported version is: 565.77.0
2025-05-12 19:35:42.517874: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:163] kernel reported version is: 565.77.0
2025-05-12 19:35:42.517881: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:241] kernel version seems to match DSO: 565.77.0

                      LSBR^   LSBM          SteganoGAN    HILL          UNIWARD *
---------------------------------------------------------------------------------
error: 'WS' undefined near line 1, column 1
Traceback (most recent call last):
  File "/mnt/761C949F1C945C45/BTP_WORK/SNN/snnenv/lib/python3.10/site-packages/scipy/io/matlab/_mio.py", line 39, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpl9n2hsu3/data.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/761C949F1C945C45/BTP_WORK/SNN/Host_Codes/sound_images_output_encrypted/./aletheia.py", line 290, in <module>
    main()
  File "/mnt/761C949F1C945C45/BTP_WORK/SNN/Host_Codes/sound_images_output_encrypted/./aletheia.py", line 47, in main
    options.auto.auto()
  File "/mnt/761C949F1C945C45/BTP_WORK/SNN/snnenv/lib/python3.10/site-packages/aletheialib/options/auto.py", line 269, in auto
    beta = O._attack('WS', bitmap_files[i], params={"channel":1})["data"][0][0]
  File "/mnt/761C949F1C945C45/BTP_WORK/SNN/snnenv/lib/python3.10/site-packages/aletheialib/octave_interface.py", line 300, in _attack
    data=loadmat(data_path)
  File "/mnt/761C949F1C945C45/BTP_WORK/SNN/snnenv/lib/python3.10/site-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/mnt/761C949F1C945C45/BTP_WORK/SNN/snnenv/lib/python3.10/site-packages/scipy/io/matlab/_mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/mnt/761C949F1C945C45/BTP_WORK/SNN/snnenv/lib/python3.10/site-packages/scipy/io/matlab/_mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpl9n2hsu3/data.mat'

**Comment by daniellerch** [comment]
The issue was caused by a missing dependency that was not being properly checked. This has now been fixed and the dependency is correctly validated.

Please update to the latest version and try again. It should work now.

Thanks again for reporting it!
